import type { SeasonalThemeConfig, SeasonalThemeKey } from '@/modules/seasonal/types'

export const SEASONAL_THEME_REGISTRY: Record<SeasonalThemeKey, SeasonalThemeConfig> = {
  default: {
    key: 'default',
    label: 'Default',
    heroVariant: 'default',
    illustrationVariant: 'store',
    backgroundVariant: 'store',
    sectionStyleVariant: 'default',
    badgeVariant: 'default',
    announcementVariant: 'default',
    loadingPreset: 'default',
    scrollPreset: 'default',
  },
  christmas: {
    key: 'christmas',
    label: 'Christmas',
    heroVariant: 'christmas',
    illustrationVariant: 'limited',
    backgroundVariant: 'christmas',
    sectionStyleVariant: 'festive',
    badgeVariant: 'gift',
    announcementVariant: 'christmas',
    loadingPreset: 'christmas',
    scrollPreset: 'soft',
  },
  halloween: {
    key: 'halloween',
    label: 'Halloween',
    heroVariant: 'halloween',
    illustrationVariant: 'support',
    backgroundVariant: 'halloween',
    sectionStyleVariant: 'spooky',
    badgeVariant: 'spooky',
    announcementVariant: 'halloween',
    loadingPreset: 'halloween',
    scrollPreset: 'dramatic',
  },
  newyear: {
    key: 'newyear',
    label: 'New Year',
    heroVariant: 'newyear',
    illustrationVariant: 'limited',
    backgroundVariant: 'newyear',
    sectionStyleVariant: 'newyear',
    badgeVariant: 'celebrate',
    announcementVariant: 'newyear',
    loadingPreset: 'newyear',
    scrollPreset: 'soft',
  },
}
