export default {
  routes: [
    {
      method: 'POST',
      path: '/analytics-events/public',
      handler: 'analytics-event.publicTrack',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/analytics-events/ops/summary',
      handler: 'analytics-event.opsSummary',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/bi/overview',
      handler: 'analytics-event.internalBiOverview',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/bi/cohorts',
      handler: 'analytics-event.internalBiCohorts',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/bi/export.csv',
      handler: 'analytics-event.internalBiExportCsv',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/bi/alerts',
      handler: 'analytics-event.internalBiAlerts',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/bi/report',
      handler: 'analytics-event.internalBiReport',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/automation/playbooks',
      handler: 'analytics-event.internalAutomationPlaybooks',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/operations/dashboard',
      handler: 'analytics-event.internalOperationsDashboard',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/releases/dashboard',
      handler: 'analytics-event.internalReleaseDashboard',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/flags/dashboard',
      handler: 'analytics-event.internalFlagDashboard',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/flags/evaluation',
      handler: 'analytics-event.internalFlagEvaluation',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/support-policies/dashboard',
      handler: 'analytics-event.internalSupportPolicyDashboard',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/flags/action',
      handler: 'analytics-event.internalFlagAction',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/releases/action',
      handler: 'analytics-event.internalReleaseAction',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/support-policies/action',
      handler: 'analytics-event.internalSupportPolicyAction',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/operations/safe-action',
      handler: 'analytics-event.internalOperationsSafeAction',
      config: { auth: false },
    },

    {
      method: 'POST',
      path: '/internal/operations/scheduled-checks/run',
      handler: 'analytics-event.internalScheduledChecksRun',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/status/public-summary',
      handler: 'analytics-event.publicStatusSummary',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/incidents/dashboard',
      handler: 'analytics-event.internalIncidentDashboard',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/incidents/triage',
      handler: 'analytics-event.internalIncidentTriageAction',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/incidents/communications/dashboard',
      handler: 'analytics-event.internalIncidentCommunicationsDashboard',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/incidents/communications/publish',
      handler: 'analytics-event.internalIncidentCommunicationPublish',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/operations/approval',
      handler: 'analytics-event.internalApprovalAction',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/operations/batch',
      handler: 'analytics-event.internalBatchOperationAction',
      config: { auth: false },
    },
    {
      method: 'GET',
      path: '/internal/automation/runs',
      handler: 'analytics-event.internalAutomationRuns',
      config: { auth: false },
    },
    {
      method: 'POST',
      path: '/internal/automation/run',
      handler: 'analytics-event.internalAutomationRun',
      config: { auth: false },
    },
  ],
}
