import { fanclubLink, storeLink, isStoreSite } from '@/lib/siteLinks'

/** ルートパスの定数 */
export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  WORKS: '/works',
  WORK_DETAIL: '/works/:slug',
  NEWS: '/news',
  NEWS_DETAIL: '/news/:slug',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:slug',
  FANCLUB: '/fanclub',
  FANCLUB_DETAIL: '/fanclub/:slug',
  EVENTS: '/events',
  EVENT_DETAIL: '/events/:slug',
  CONTACT: '/contact',
  STORE: '/store',
  STORE_DETAIL: '/store/:handle',
  CART: '/store/cart',
  MEMBER: '/member',
  PRICING: '/pricing',
  FAQ: '/faq',
  LEGAL_PRIVACY: '/legal/privacy-policy',
  LEGAL_TERMS: '/legal/terms',
  LEGAL_COOKIE: '/legal/cookie-policy',
  LEGAL_TRADE: '/legal/tokushoho',
  PREVIEW: '/preview',
  STORE_HOME: '/',
  STORE_PRODUCTS: '/products',
  STORE_PRODUCT_DETAIL: '/products/:handle',
  STORE_COLLECTION: '/collections/:slug',
  STORE_CAMPAIGN: '/campaigns/:slug',
  STORE_ARTIST: '/artists/:slug',
  STORE_SERIES: '/series/:slug',
  STORE_GUIDE: '/guide',
  STORE_SHIPPING_POLICY: '/shipping-policy',
  STORE_RETURNS: '/returns',
  STORE_CONTACT: '/contact',
  STORE_LEGAL: '/legal',
  STORE_TERMS: '/terms',
  STORE_PRIVACY: '/privacy',
  STORE_CART: '/cart',
  STORE_CHECKOUT_SUCCESS: '/checkout/success',
  STORE_CHECKOUT_CANCEL: '/checkout/cancel',

  FC_ABOUT: '/about',
  FC_JOIN: '/join',
  FC_LOGIN: '/login',
  FC_LOGIN_RESET_PASSWORD: '/login/reset-password',
  FC_LOGIN_VERIFY_EMAIL: '/login/verify-email',
  FC_MYPAGE: '/mypage',
  FC_MOVIES: '/movies',
  FC_MOVIE_DETAIL: '/movies/:slug',
  FC_GALLERY: '/gallery',
  FC_GALLERY_DETAIL: '/gallery/:slug',
  FC_SCHEDULE: '/schedule',
  FC_TICKETS: '/tickets',
  FC_TICKET_DETAIL: '/tickets/:slug',
  FC_MEMBER_STORE: '/member-store',
  FC_CAMPAIGN: '/campaigns/:slug',
  FC_GUIDE: '/guide',
  FC_LEGAL: '/legal',
  FC_TERMS: '/terms',
  FC_PRIVACY: '/privacy',
  FC_COMMERCE_LAW: '/commerce-law',
  FC_SUBSCRIPTION_POLICY: '/subscription-policy',
  FC_CHECKOUT_SUCCESS: '/checkout/success',
  FC_CHECKOUT_CANCEL: '/checkout/cancel',
} as const

/** 詳細ページへの URL を生成する */
export const detailPath = {
  news: (slug: string) => `/news/${slug}`,
  blog: (slug: string) => `/blog/${slug}`,
  work: (slug: string) => `/works/${slug}`,
  fanclub: (slug: string) => fanclubLink(`/fanclub/${slug}`),
  event: (slug: string) => `/events/${slug}`,
  product: (handle: string) => (isStoreSite ? `/products/${handle}` : storeLink(`/store/${handle}`)),
} as const
